/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-125300-g1499c4ac6d-20260625"
#endif /* AVUTIL_FFVERSION_H */
